import logging
from typing import Optional

import google.auth.transport.requests
from google.oauth2 import service_account

from utilities.json_request_util import HttpJsonRequestor


class PlayIntegrityClient:
    """Google Play Integrity API client.

    Authenticates using a Google service account and calls the
    decodeIntegrityToken endpoint to verify Android integrity tokens.

    Reference:
        https://developer.android.com/google/play/integrity/verdict
    """

    PLAY_INTEGRITY_SCOPE = "https://www.googleapis.com/auth/playintegrity"
    BASE_URL = "https://playintegrity.googleapis.com"
    DECODE_ENDPOINT = "/v1/{package_name}:decodeIntegrityToken"

    def __init__(
        self,
        service_account_info: dict,
        package_name: str,
        logger: logging.Logger,
    ):
        """Initialises the client.

        Args:
            service_account_info: Parsed dict from the Google service account JSON file.
            package_name: Android application package name (e.g. com.example.myapp).
            logger: Logger instance.
        """
        self._service_account_info = service_account_info
        self._package_name = package_name
        self._logger = logger

    def _get_access_token(self) -> Optional[str]:
        """Obtains a short-lived OAuth2 access token using the service account.

        Returns:
            Bearer token string, or None on failure.
        """
        try:
            credentials = service_account.Credentials.from_service_account_info(
                self._service_account_info,
                scopes=[self.PLAY_INTEGRITY_SCOPE],
            )
            auth_req = google.auth.transport.requests.Request()
            credentials.refresh(auth_req)
            return credentials.token
        except Exception as e:
            self._logger.error(f"[PlayIntegrityClient] Failed to obtain access token: {e}")
            return None

    def decode_integrity_token(self, integrity_token: str) -> dict:
        """Calls Google Play Integrity API to decode and verify an integrity token.

        Args:
            integrity_token: The integrity token generated by the Android client.

        Returns:
            dict with keys:
                - is_success (bool)
                - data (dict | None): tokenPayloadExternal on success
                - error (str | None): error message on failure
        """
        access_token = self._get_access_token()
        if not access_token:
            return {
                "is_success": False,
                "data": None,
                "error": "Failed to obtain Google OAuth2 access token.",
            }

        endpoint = self.DECODE_ENDPOINT.format(package_name=self._package_name)

        requestor = HttpJsonRequestor(self.BASE_URL, logger=self._logger)
        requestor.set_header("Authorization", f"Bearer {access_token}")

        self._logger.info(
            f"[PlayIntegrityClient] Calling decodeIntegrityToken for package={self._package_name}"
        )

        response = requestor.post(
            endpoint,
            body_params={"integrity_token": integrity_token},
        )

        if response.is_ok:
            payload = response.content.get("tokenPayloadExternal", {})
            self._logger.info(
                f"[PlayIntegrityClient] Token decoded successfully. "
                f"appRecognitionVerdict={payload.get('appIntegrity', {}).get('appRecognitionVerdict')}"
            )
            return {"is_success": True, "data": payload, "error": None}

        error_msg = (
            response.content.get("error", {}).get("message", "Unknown error")
            if response.content
            else "No response from Google Play Integrity API"
        )
        self._logger.error(
            f"[PlayIntegrityClient] decodeIntegrityToken failed. "
            f"Status={response.status_code} Error={error_msg}"
        )
        return {"is_success": False, "data": None, "error": error_msg}
